_wandb:
    value:
        cli_version: 0.22.2
        e:
            8w5p2pvjxegb4lq042hvza88r0arsbu2:
                args:
                    - --dataset.repo_id=bluephysi01/so101_test34
                    - --policy.path=lerobot/smolvla_base
                    - --policy.device=cuda
                    - --policy.chunk_size=30
                    - --policy.n_action_steps=30
                    - --policy.n_obs_steps=60
                    - --batch_size=16
                    - --num_workers=8
                    - --job_name=smolvla_so101_test34-1
                    - --policy.push_to_hub=true
                    - --policy.repo_id=bluephysi01/smolvla_so101_test34-1
                    - --steps=50000
                    - --wandb.enable=true
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982820896768"
                        used: "382517719040"
                executable: /home/bluephysi01/lerobot/.venv/bin/python
                git:
                    commit: b74e2a61133b695eca35997334f22389321ed6db
                    remote: https://github.com/huggingface/lerobot.git
                gpu: NVIDIA GeForce RTX 5050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5050 Laptop GPU
                      uuid: GPU-ad58112f-75ab-dbfc-5641-55a627c52ebe
                host: bluephysi01-LOQ-15IRX10
                memory:
                    total: "33344606208"
                os: Linux-6.8.0-88-generic-x86_64-with-glibc2.35
                program: -m lerobot.scripts.lerobot_train
                python: CPython 3.10.12
                root: outputs/train/2025-12-20/08-01-25_smolvla_so101_test34-1
                startedAt: "2025-12-19T23:01:26.006321Z"
                writerId: 8w5p2pvjxegb4lq042hvza88r0arsbu2
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "6": 4.53.3
            "10":
                - 21
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 16
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: bluephysi01/so101_test34
        revision: null
        root: null
        streaming: false
        use_imagenet_stats: true
        video_backend: pyav
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 20000
job_name:
    value: smolvla_so101_test34-1
log_freq:
    value: 200
num_workers:
    value: 8
optimizer:
    value:
        betas:
            - 0.9
            - 0.95
        eps: 1e-08
        grad_clip_norm: 10
        lr: 0.0001
        type: adamw
        weight_decay: 1e-10
output_dir:
    value: outputs/train/2025-12-20/08-01-25_smolvla_so101_test34-1
policy:
    value:
        adapt_to_pi_aloha: false
        add_image_special_tokens: false
        attention_mode: cross_attn
        chunk_size: 30
        device: cuda
        empty_cameras: 0
        expert_width_multiplier: 0.75
        freeze_vision_encoder: true
        input_features:
            observation.images.camera1:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.camera2:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.camera3:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.state:
                shape:
                    - 6
                type: STATE
        license: null
        load_vlm_weights: true
        max_action_dim: 32
        max_period: 4
        max_state_dim: 32
        min_period: 0.004
        n_action_steps: 30
        n_obs_steps: 60
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        num_expert_layers: 0
        num_steps: 10
        num_vlm_layers: 16
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_grad_clip_norm: 10
        optimizer_lr: 0.0001
        optimizer_weight_decay: 1e-10
        output_features:
            action:
                shape:
                    - 6
                type: ACTION
        pad_language_to: max_length
        prefix_length: 0
        pretrained_path: lerobot/smolvla_base
        private: null
        push_to_hub: true
        repo_id: bluephysi01/smolvla_so101_test34-1
        resize_imgs_with_padding:
            - 512
            - 512
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        self_attn_every_n_layers: 2
        tags: null
        tokenizer_max_length: 48
        train_expert_only: true
        train_state_proj: true
        type: smolvla
        use_amp: false
        use_cache: true
        use_delta_joint_actions_aloha: false
        vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 20000
scheduler:
    value:
        decay_lr: 2.5e-06
        num_decay_steps: 30000
        num_warmup_steps: 1000
        peak_lr: 0.0001
        type: cosine_decay_with_warmup
seed:
    value: 1000
steps:
    value: 50000
use_policy_training_preset:
    value: true
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null
